kind: HTTPRoute
apiVersion: gateway.networking.k8s.io/v1beta1
metadata:
  name: gateway-routes
spec:
  parentRefs:
  - kind: Gateway
    name: external-http
  - kind: Gateway
    name: internal-http
  hostnames:
  - gateway.searce-aben.com
  rules:
  - backendRefs:
    - name: un
      port: 8080
  