apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: prod-issuer
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: saikiran.gcp7@gmail.com
    privateKeySecretRef:
      name: prod-secret
    solvers:
    - dns01:
        cloudDNS:
          project: ce-ps-3team
          hostedZoneName: polygon-test-aben
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: prod-cert
  namespace: default
spec:
  secretName: cert-secret
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
    rotationPolicy: Always
  duration: 2h # 30d
  renewBefore: 1h # 1d
  issuerRef:
    name: prod-issuer
    kind: ClusterIssuer
  dnsNames:
  - "*.searce-aben.com"
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-ingress
  annotations:
    cert-manager.io/issuer: prod-issuer
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - nginx-web.searce-aben.com
    secretName: cert-secret
  rules:
  - host: nginx-web.searce-aben.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: neo
            port:
              number: 80
