apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: aben.george@searce.com
    privateKeySecretRef:
      name: letsencrypt-staging
    solvers:
    - dns01:
          cloudDNS:
            project: ce-ps-3team
            hostedZoneName: gangadhars-ce-ps6
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: example-cert
  namespace: default
spec:
  secretName: example-cert
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
  commonName: app.cloud.ce-ps6.team
  dnsNames:
  - app.cloud.ce-ps6.team
